// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function GreetinForUser(arg1) {
  return window['go']['main']['App']['GreetinForUser'](arg1);
}

export function InstallApplications(arg1) {
  return window['go']['main']['App']['InstallApplications'](arg1);
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}
